### ISSUE TITLE
 .ToXamlString() ? How to return WPF Xaml Geometry Path as string

### ISSUE THREAD

**Issue by ps30** [manuelbl/QrCodeGenerator#11]
There is now a .ToSvgString() method to return the SVG text string, but WPF needs the QR Code in a Geometry Path format to be consumed by an `<Image>` or `<Viewbox>` control.  How can I get the text string of the QR Code as a Xaml Geometry Path with this library?  If it cannot be extracted currently, could you add a **.ToXamlString()** method? Thank you, example and link to Geometry below.

Example:
```
string 2DBarcodePath = qrCode.ToXamlString(3);

<Viewbox
       Width="100"
       Height="100"
       Stretch="Uniform">
       <Path x:Name="2DBarcodePath" Fill="Black" />
</Viewbox>
```

[Geometry Overview](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/geometry-overview?view=netframeworkdesktop-4.8)

**Comment by manuelbl** [comment]
Thanks for the suggestion. I will look into it.

When using WPF, you might want to have a look at the WPF example: https://github.com/manuelbl/QrCodeGenerator/tree/master/Demo-WindowsPresentationFoundation and in particular at the [QrCodeDrawing](https://github.com/manuelbl/QrCodeGenerator/blob/master/Demo-WindowsPresentationFoundation/QrCodeDrawing.cs) class. It creates a drawing visual that can be easily displayed in a WPF UI.

**Comment by ps30** [comment]
Thank you for the reply, and I did review and compiled the excellent demo examples you created including the WPF code.  It works perfectly, but we use WPF icons & images composed as geometry.path.data strings of text (almost the same as SVG text) to easily updated Xaml containers to display different images including QR codes.  For example, we can send a simple text string to the control and it will render a red alert icon image or a blue question mark icon image using only text. If the QR code generator could output Xaml path text then these controls could display the QR code.

If you added a method like .ToXamlString() that returns a string with only the Path.Data that could be passed to other WPF/UWP/MAUI Xaml controls to render the QR code as an image.

Here is a great free icon site that lets you download SVG or Xaml text for icon images: [materialdesignicons.com](https://materialdesignicons.com/)

SVG text:
`<path fill="currentColor" d="M2,6H4V18H2V6M5,6H6V18H5V6M7,6H10V18H7V6M11,6H12V18H11V6M14,6H16V18H14V6M17,6H20V18H17V6M21,6H22V18H21V6Z" />`

Xaml text:
`<Path Fill="Black" Data="M2,6H4V18H2V6M5,6H6V18H5V6M7,6H10V18H7V6M11,6H12V18H11V6M14,6H16V18H14V6M17,6H20V18H17V6M21,6H22V18H21V6Z" />`

So returning only the Data text or "M2,6H4V18H2V6M5,6H6V18H5V6M7,6H10V18H7V6M11,6H12V18H11V6M14,6H16V18H14V6M17,6H20V18H17V6M21,6H22V18H21V6Z" as a string.

**Comment by manuelbl** [comment]
> returns a string with only the Path.Data that could be passed to other WPF/UWP/MAUI Xaml controls to render the QR code as an image

Can you provide an example for that? As far as I can see, if data binding is used, *Path.Data* requires a *Geometry* instance. A string won't do.

Or does your use case look differently? Do you copy the Xaml path into the code before compiling the software?

**Comment by ps30** [comment]
We have been using [ZXing.Net](https://github.com/micjahn/ZXing.Net) project on Github.  This library does the barcode export to geometry.path.data as a text string and works but it is a heavy package with all barcode types for encoding and decoding. For example this is how we create a 2D barcode and export to the geometry path plain text and then display via MVVM binding in a WPF control:
```
            var writer = new BarcodeWriterGeometry
            {
                Format = BarcodeFormat.DATA_MATRIX,
                Options = new ZXing.Common.EncodingOptions { Height = 1, Width = 1, Margin = 2 }
            };
            string PathImageData = writer.Write("Hello this is a test").ToString();
```
Now PathImageData is a string that contains the barcode path data and you can use that text in a Xaml WPF control to display the barcode:
```
            _xDataMatrixPath.SetBinding(
                Path.DataProperty,
                new Binding(nameof(vm.PathImageData)) { Mode = BindingMode.OneWay, TargetNullValue = "" });
```
```
                <Viewbox
                    Width="100"
                    Height="100"
                    Stretch="Uniform">
                    <Path x:Name="_xDataMatrixPath" Fill="Black" />
                </Viewbox>
```

For more detail you could look at [ZXing.Net](https://github.com/micjahn/ZXing.Net) source for the .ToString() overload that outputs the barcode as Xaml path data.

**Comment by manuelbl** [comment]
Version 2.0.3 has been published. It adds a new method [ToGraphicsPath(Int32)](https://codecrete.net/QrCodeGenerator/api/Net.Codecrete.QrCodeGenerator.QrCode.html#Net_Codecrete_QrCodeGenerator_QrCode_ToGraphicsPath_System_Int32_) that should do what you are looking for.

**Comment by ps30** [comment]
@manuelbl downloaded, tested, and works.  Thank you for adding this great feature for Xaml use.  I will close this issue now.
