### ISSUE TITLE
A sample for Magick.NET to create image

### ISSUE THREAD

**Issue by suxiaobu9** [manuelbl/QrCodeGenerator#13]
Hi

This is a sample to create image by [Magick.NET](https://github.com/dlemstra/Magick.NET)

[Demo-ImageMagick.zip](https://github.com/manuelbl/QrCodeGenerator/files/9186628/Demo-ImageMagick.zip)

**Comment by manuelbl** [comment]
Thanks for the code. I've added it to the repo.
