### ISSUE TITLE
QR Code as svg path not rendered on some mobile phone models

### ISSUE THREAD

**Issue by svetvasilev** [manuelbl/QrCodeGenerator#20]
QR code that is generated as an SVG path (through invocation to QrCode.ToGraphicsPath()) is not getting rendered on the screen for some mobile phone models. Particularly when testing on my OnePlus Nord 2 this was indeed the case. It runs latest version of OxyOS (android 13). The QR code is however rendered successfully in the emulator (Pixel 5, Android 11). After debugging the code and fetching the path string that is generated when running on the phone and comparing it to the one taken from the emulator, it turned out that the issue is caused by a rather subtle circumstance. The path contains instructions in the form of Mx,yhAvBh-Az, where x, y are coordinates of the starting point of a rectangle, while A and B are respectively horizontal and vertical line lengths. The "-" sign before the last horizontal length says that the line will be drawn in the opposite direction. This character was generated on my phone as "−". I literally felt like my eyeballs would pop out of orbit when i was examining what the heck is the difference between the 2 path strings. I guess anybody would feel the same way, as there was literally no visible difference. Until VS Code compare come to rescue! Now when putting the 2 chars one next to each other it is much more obvious - "−" vs "-"! I guess this is due to locale settings. My phone is in Norwegian local, so this might be an issue with many other locales as well.
In order to fix this issue in needs to be assured that the "-" sign is char 0x2d, and not 0xe2 0x88 0x92 ("−").

**Comment by manuelbl** [comment]
Thank you very much for reporting this problem, and for the analysis. I'll look into it.

**Comment by manuelbl** [comment]
The issue has been fixed in version 2.0.4.
