### ISSUE TITLE
Support for other project types.

### ISSUE THREAD

**Issue by brrick** [manuelbl/QrCodeGenerator#21]
Not an issue per se, but trying to create a Maui Blazor Desktop app. Looking to have an SVG export option. Is this something that can be done?

**Comment by manuelbl** [comment]
What would an "SVG export option" look like? Saving the generated SVG as a file? Or saving it in another format than SVG? Or a different media than file?

**Comment by brrick** [comment]
I would want to save it out as an SVG file. Being able to scale for other programs and software to create labels of all sizes would be awesome.

**Comment by manuelbl** [comment]
Is that mostly covered already?

```
var qr = QrCode.EncodeText("Hello, world!", QrCode.Ecc.Medium);
string svg = qr.ToSvgString(4);
File.WriteAllText("qrcode.svg", svg, Encoding.UTF8);
```

Or what would be needed in addition?

**Comment by brrick** [comment]
Thanks.
