### ISSUE TITLE
Byte Encoding version.

### ISSUE THREAD

**Issue by desconfiado** [manuelbl/QrCodeGenerator#3]
Hi.

Is it possible to generate encoding in Byte format and specify the version?
The Byte generator only allows to specify the message in Byte array and the ecc correction level but not the version.

**Comment by manuelbl** [comment]
The *version* of the QR code is basically the *size*. It determines the number of pixels used in the QR code. The longer the data, the higher the version that will be needed to put all the data into the QR code.

For the given data and the given correction level, the library tests different parameters and then chooses the parameters resulting in the smallest version.

In short: data determines version and not the other way round.
