### ISSUE TITLE
Changeable Content

### ISSUE THREAD

**Issue by Researcher33** [manuelbl/QrCodeGenerator#6]
Hi, How can we update the information we added to the qr code without changing the qr code. The program will generate a qr code. The content will be changed without changing the qr code. How can i do ?

**Comment by manuelbl** [comment]
I'm afraid I don't understand the question. Can you provide more context and/or a code sample?

**Comment by Researcher33** [comment]
I found some answers. I installed the qr encoder in this link.(https://github.com/giandonatoinverso/PHP-Dynamic-Qr-code)
 But it doesn't redirect to qr url. I'm new to coding, can you help me use it? please

**Comment by manuelbl** [comment]
[PHP-Dynamic-Qr-code](https://github.com/giandonatoinverso/PHP-Dynamic-Qr-code) is not related to this project in a way. It has different authors, uses a different technology and provides different features. Please ask question about it in that project's issue section.
