### ISSUE TITLE
Is it possible to embed an image?

### ISSUE THREAD

**Issue by gabrielmaldi** [manuelbl/QrCodeGenerator#7]
Hi, first of all thanks for this great project! 💪🏻 

Is it possible to embed an image (probably a logo) in the center of the QR code image? Like [QRCode Monkey](https://www.qrcode-monkey.com)'s `ADD LOGO IMAGE` feature. Or as discussed in this other project: https://github.com/codebude/QRCoder/issues/232

I'm using the `Demo-ImageSharp` sample.

Thanks!

**Comment by manuelbl** [comment]
This library does not directly support adding an image as such a feature is very dependent on the imaging library being used.

For most imaging library, it's straight-forward to achieve. I've exteneded the [Demo-ImageSharp](https://github.com/manuelbl/QrCodeGenerator/tree/master/Demo-ImageSharp) sample code to additionally create a QR code with an image. I hope it's helpful for your purpose.

**Comment by gabrielmaldi** [comment]
Wow, thank you very much for this great example and quick reply!

That worked perfectly, I will adapt it to my needs.

Thanks again!
