### ISSUE TITLE
how to change qrcode ‘s color?

### ISSUE THREAD

**Issue by CristWu** [manuelbl/QrCodeGenerator#8]

**Comment by manuelbl** [comment]
`QrCode.ToSvgString(Int32, String, String)` takes a foreground and a background color.

See [QrCode.ToSvgString(Int32, String, String)](https://codecrete.net/QrCodeGenerator/api/Net.Codecrete.QrCodeGenerator.QrCode.html#Net_Codecrete_QrCodeGenerator_QrCode_ToSvgString_System_Int32_System_String_System_String_)
