### ISSUE TITLE
Error in the readme.md Manual operation Section

### ISSUE THREAD

**Issue by TobiVanHelsinki** [manuelbl/QrCodeGenerator#9]
In the main readme.md of this repo, in section **Manual operation** there is Line 91:
"var segments = QrCode.MakeSegments("3141592653589793238462643383");"

I tried the example but QrCode for me has no member "MakeSegments". However if i change QrCode to QrSegment it works like a charm. Maybe a typo?

Regards Tobi

**Comment by manuelbl** [comment]
Thanks for pointing out this error. I've fixed it.
